Team { 
	id: 116
	location: "Mount St. Mary's"
	name: "Mountaineers"
	display_name: "Mt St Mary"
	abbreviation: "MSM"
	primary_color {
		red: 0
		green: 85
		blue: 150
	}
	secondary_color: {
		red: 235
		green: 235
		blue: 235
	}
}
Team { 
	id: 276
	location: "Marshall"
	name: "Thundering Herd"
	display_name: "Marshall"
	abbreviation: "MRSH"
	primary_color {
		red: 24
		green: 99
		blue: 41
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 253
	location: "Southern Utah"
	name: "Thunderbirds"
	display_name: "S Utah"
	abbreviation: "SUU"
	primary_color {
		red: 209
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 331
	location: "Eastern Washington"
	name: "Eagles"
	display_name: "E Wash"
	abbreviation: "EWU"
	primary_color {
		red: 161
		green: 0
		blue: 34
	}
	secondary_color: {
		red: 171
		green: 180
		blue: 188
	}
}
Team { 
	id: 16
	location: "Sacramento State"
	name: "Hornets"
	display_name: "Sac St"
	abbreviation: "SAC"
	primary_color {
		red: 0
		green: 87
		blue: 60
	}
	secondary_color: {
		red: 205
		green: 185
		blue: 125
	}
}
Team { 
	id: 2306
	location: "Kansas State"
	name: "Wildcats"
	display_name: "Kansas St"
	abbreviation: "KSU"
	primary_color {
		red: 99
		green: 49
		blue: 148
	}
	secondary_color: {
		red: 231
		green: 210
		blue: 173
	}
}
Team { 
	id: 399
	location: "Albany"
	name: "Great Danes"
	display_name: "Albany"
	abbreviation: "ALB"
	primary_color {
		red: 61
		green: 39
		blue: 119
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 233
	location: "South Dakota"
	name: "Coyotes"
	display_name: "S Dakota"
	abbreviation: "SDAK"
	primary_color {
		red: 205
		green: 18
		blue: 65
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 2197
	location: "Eastern Illinois"
	name: "Panthers"
	display_name: "E Illinois"
	abbreviation: "EIU"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 190
		green: 186
		blue: 185
	}
}
Team { 
	id: 2239
	location: "CSU Fullerton"
	name: "Titans"
	display_name: "Fullerton"
	abbreviation: "CSUF"
	primary_color {
		red: 16
		green: 33
		blue: 156
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 103
	location: "Boston College"
	name: "Eagles"
	display_name: "Boston C"
	abbreviation: "BC"
	primary_color {
		red: 136
		green: 0
		blue: 26
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 269
	location: "Marquette"
	name: "Golden Eagles"
	display_name: "Marquette"
	abbreviation: "MARQ"
	primary_color {
		red: 8
		green: 57
		blue: 99
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 155
	location: "North Dakota"
	name: "Fighting Hawks"
	display_name: "N Dakota"
	abbreviation: "UND"
	primary_color {
		red: 0
		green: 162
		blue: 107
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 13
	location: "Cal Poly"
	name: "Mustangs"
	display_name: "Cal Poly"
	abbreviation: "CP"
	primary_color {
		red: 30
		green: 77
		blue: 43
	}
	secondary_color: {
		red: 238
		green: 216
		blue: 151
	}
}
Team { 
	id: 41
	location: "UConn"
	name: "Huskies"
	display_name: "UConn"
	abbreviation: "CONN"
	primary_color {
		red: 0
		green: 29
		blue: 64
	}
	secondary_color: {
		red: 241
		green: 242
		blue: 243
	}
}
Team { 
	id: 2086
	location: "Butler"
	name: "Bulldogs"
	display_name: "Butler"
	abbreviation: "BUT"
	primary_color {
		red: 13
		green: 19
		blue: 97
	}
	secondary_color: {
		red: 0
		green: 163
		blue: 224
	}
}
Team { 
	id: 2287
	location: "Illinois State"
	name: "Redbirds"
	display_name: "Illinois St"
	abbreviation: "ILST"
	primary_color {
		red: 206
		green: 17
		blue: 38
	}
	secondary_color: {
		red: 255
		green: 231
		blue: 22
	}
}
Team { 
	id: 290
	location: "Georgia Southern"
	name: "Eagles"
	display_name: "GA Southern"
	abbreviation: "GASO"
	primary_color {
		red: 0
		green: 55
		blue: 117
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 97
	location: "Louisville"
	name: "Cardinals"
	display_name: "Louisville"
	abbreviation: "LOU"
	primary_color {
		red: 173
		green: 0
		blue: 10
	}
	secondary_color: {
		red: 204
		green: 204
		blue: 204
	}
}
Team { 
	id: 82
	location: "UIC"
	name: "Flames"
	display_name: "UIC"
	abbreviation: "UIC"
	primary_color {
		red: 35
		green: 64
		blue: 119
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 197
	location: "Oklahoma State"
	name: "Cowboys"
	display_name: "Oklahoma St"
	abbreviation: "OKST"
	primary_color {
		red: 255
		green: 101
		blue: 0
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2250
	location: "Gonzaga"
	name: "Bulldogs"
	display_name: "Gonzaga"
	abbreviation: "GONZ"
	primary_color {
		red: 0
		green: 41
		blue: 103
	}
	secondary_color: {
		red: 207
		green: 212
		blue: 216
	}
}
Team { 
	id: 2130
	location: "Chicago State"
	name: "Cougars"
	display_name: "Chicago St"
	abbreviation: "CHIC"
	primary_color {
		red: 0
		green: 103
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 30
	location: "USC"
	name: "Trojans"
	display_name: "USC"
	abbreviation: "USC"
	primary_color {
		red: 174
		green: 37
		blue: 49
	}
	secondary_color: {
		red: 255
		green: 199
		blue: 44
	}
}
Team { 
	id: 282
	location: "Indiana State"
	name: "Sycamores"
	display_name: "Indiana St"
	abbreviation: "INST"
	primary_color {
		red: 0
		green: 102
		blue: 154
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 91
	location: "Bellarmine"
	name: "Knights"
	display_name: "Bellarmine"
	abbreviation: "BELL"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 140
	location: "UM Kansas City"
	name: "Roos"
	display_name: "UM KC"
	abbreviation: "UMKC"
	primary_color {
		red: 0
		green: 75
		blue: 135
	}
	secondary_color: {
		red: 255
		green: 199
		blue: 44
	}
}
Team { 
	id: 2142
	location: "Colgate"
	name: "Raiders"
	display_name: "Colgate"
	abbreviation: "COLG"
	primary_color {
		red: 139
		green: 1
		blue: 29
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 145
	location: "Ole Miss"
	name: "Rebels"
	display_name: "Ole Miss"
	abbreviation: "MISS"
	primary_color {
		red: 0
		green: 17
		blue: 72
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 261
	location: "Vermont"
	name: "Catamounts"
	display_name: "Vermont"
	abbreviation: "UVM"
	primary_color {
		red: 1
		green: 60
		blue: 36
	}
	secondary_color: {
		red: 255
		green: 199
		blue: 44
	}
}
Team { 
	id: 87
	location: "Notre Dame"
	name: "Fighting Irish"
	display_name: "Notre Dame"
	abbreviation: "ND"
	primary_color {
		red: 0
		green: 18
		blue: 43
	}
	secondary_color: {
		red: 174
		green: 145
		blue: 66
	}
}
Team { 
	id: 2083
	location: "Bucknell"
	name: "Bison"
	display_name: "Bucknell"
	abbreviation: "BUCK"
	primary_color {
		red: 0
		green: 0
		blue: 96
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 45
	location: "George Washington"
	name: "Colonials"
	display_name: "G Wash"
	abbreviation: "GW"
	primary_color {
		red: 0
		green: 40
		blue: 67
	}
	secondary_color: {
		red: 232
		green: 210
		blue: 161
	}
}
Team { 
	id: 2032
	location: "Arkansas State"
	name: "Red Wolves"
	display_name: "Arkansas St"
	abbreviation: "ARST"
	primary_color {
		red: 232
		green: 16
		blue: 24
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2352
	location: "Loyola (MD)"
	name: "Greyhounds"
	display_name: "Loyola (MD)"
	abbreviation: "L-MD"
	primary_color {
		red: 118
		green: 167
		blue: 160
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 61
	location: "Georgia"
	name: "Bulldogs"
	display_name: "Georgia"
	abbreviation: "UGA"
	primary_color {
		red: 204
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2154
	location: "Coppin St"
	name: "Eagles"
	display_name: "Coppin St"
	abbreviation: "COPP"
	primary_color {
		red: 46
		green: 49
		blue: 146
	}
	secondary_color: {
		red: 255
		green: 210
		blue: 4
	}
}
Team { 
	id: 6
	location: "South Alabama"
	name: "Jaguars"
	display_name: "S Alabama"
	abbreviation: "USA"
	primary_color {
		red: 0
		green: 62
		blue: 126
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 142
	location: "Missouri"
	name: "Tigers"
	display_name: "Missouri"
	abbreviation: "MIZ"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 43
	location: "Yale"
	name: "Bulldogs"
	display_name: "Yale"
	abbreviation: "YALE"
	primary_color {
		red: 0
		green: 74
		blue: 129
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 172
	location: "Cornell"
	name: "Big Red"
	display_name: "Cornell"
	abbreviation: "COR"
	primary_color {
		red: 214
		green: 0
		blue: 39
	}
	secondary_color: {
		red: 16
		green: 16
		blue: 16
	}
}
Team { 
	id: 28
	location: "UC San Diego"
	name: "Tritons"
	display_name: "UC SD"
	abbreviation: "UCSD"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 225
	location: "Brown"
	name: "Bears"
	display_name: "Brown"
	abbreviation: "BRWN"
	primary_color {
		red: 65
		green: 30
		blue: 9
	}
	secondary_color: {
		red: 148
		green: 147
		blue: 0
	}
}
Team { 
	id: 8
	location: "Arkansas"
	name: "Razorbacks"
	display_name: "Arkansas"
	abbreviation: "ARK"
	primary_color {
		red: 156
		green: 24
		blue: 49
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 279
	location: "Pacific"
	name: "Tigers"
	display_name: "Pacific"
	abbreviation: "PAC"
	primary_color {
		red: 244
		green: 120
		blue: 32
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 201
	location: "Oklahoma"
	name: "Sooners"
	display_name: "Oklahoma"
	abbreviation: "OU"
	primary_color {
		red: 123
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 204
		green: 204
		blue: 204
	}
}
Team { 
	id: 309
	location: "Louisiana"
	name: "Ragin' Cajuns"
	display_name: "Louisiana"
	abbreviation: "ULL"
	primary_color {
		red: 206
		green: 40
		blue: 66
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2132
	location: "Cincinnati"
	name: "Bearcats"
	display_name: "Cincinnati"
	abbreviation: "CIN"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 113
		green: 112
		blue: 115
	}
}
Team { 
	id: 2031
	location: "Little Rock"
	name: "Trojans"
	display_name: "Little Rock"
	abbreviation: "UALR"
	primary_color {
		red: 173
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2127
	location: "Charleston Southern"
	name: "Buccaneers"
	display_name: "Charleston S"
	abbreviation: "CHSO"
	primary_color {
		red: 46
		green: 49
		blue: 146
	}
	secondary_color: {
		red: 222
		green: 208
		blue: 144
	}
}
Team { 
	id: 238
	location: "Vanderbilt"
	name: "Commodores"
	display_name: "Vanderbilt"
	abbreviation: "VAN"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 277
	location: "West Virginia"
	name: "Mountaineers"
	display_name: "W Virginia"
	abbreviation: "WVU"
	primary_color {
		red: 255
		green: 198
		blue: 0
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 99
	location: "LSU"
	name: "Tigers"
	display_name: "LSU"
	abbreviation: "LSU"
	primary_color {
		red: 43
		green: 13
		blue: 87
	}
	secondary_color: {
		red: 253
		green: 208
		blue: 35
	}
}
Team { 
	id: 2115
	location: "Central Connecticut"
	name: "Blue Devils"
	display_name: "Cent Conn"
	abbreviation: "CCSU"
	primary_color {
		red: 27
		green: 73
		blue: 162
	}
	secondary_color: {
		red: 209
		green: 213
		blue: 216
	}
}
Team { 
	id: 58
	location: "South Florida"
	name: "Bulls"
	display_name: "S Florida"
	abbreviation: "USF"
	primary_color {
		red: 0
		green: 74
		blue: 54
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2110
	location: "Central Arkansas"
	name: "Bears"
	display_name: "Cent Ark"
	abbreviation: "UCA"
	primary_color {
		red: 167
		green: 169
		blue: 172
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 50
	location: "Florida A&M"
	name: "Rattlers"
	display_name: "Florida A&M"
	abbreviation: "FAMU"
	primary_color {
		red: 248
		green: 151
		blue: 40
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 194
	location: "Ohio State"
	name: "Buckeyes"
	display_name: "Ohio State"
	abbreviation: "OSU"
	primary_color {
		red: 187
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 166
	location: "New Mexico State"
	name: "Aggies"
	display_name: "New Mex St"
	abbreviation: "NMSU"
	primary_color {
		red: 137
		green: 18
		blue: 22
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2057
	location: "Belmont"
	name: "Bruins"
	display_name: "Belmont"
	abbreviation: "BEL"
	primary_color {
		red: 24
		green: 33
		blue: 66
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 120
	location: "Maryland"
	name: "Terrapins"
	display_name: "Maryland"
	abbreviation: "MD"
	primary_color {
		red: 213
		green: 0
		blue: 43
	}
	secondary_color: {
		red: 255
		green: 205
		blue: 0
	}
}
Team { 
	id: 249
	location: "North Texas"
	name: "Mean Green"
	display_name: "North Texas"
	abbreviation: "UNT"
	primary_color {
		red: 0
		green: 133
		blue: 61
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2294
	location: "Iowa"
	name: "Hawkeyes"
	display_name: "Iowa"
	abbreviation: "IOWA"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 225
		blue: 0
	}
}
Team { 
	id: 70
	location: "Idaho"
	name: "Vandals"
	display_name: "Idaho"
	abbreviation: "IDHO"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 140
		green: 110
		blue: 74
	}
}
Team { 
	id: 23
	location: "San José St"
	name: "Spartans"
	display_name: "San José St"
	abbreviation: "SJSU"
	primary_color {
		red: 0
		green: 88
		blue: 147
	}
	secondary_color: {
		red: 253
		green: 186
		blue: 49
	}
}
Team { 
	id: 96
	location: "Kentucky"
	name: "Wildcats"
	display_name: "Kentucky"
	abbreviation: "UK"
	primary_color {
		red: 0
		green: 93
		blue: 170
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2066
	location: "Binghamton"
	name: "Bearcats"
	display_name: "Binghamton"
	abbreviation: "BING"
	primary_color {
		red: 0
		green: 97
		blue: 74
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 2241
	location: "Gardner-Webb"
	name: "Bulldogs"
	display_name: "Gardner W"
	abbreviation: "GWEB"
	primary_color {
		red: 193
		green: 37
		blue: 53
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2230
	location: "Fordham"
	name: "Rams"
	display_name: "Fordham"
	abbreviation: "FOR"
	primary_color {
		red: 131
		green: 0
		blue: 50
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2
	location: "Auburn"
	name: "Tigers"
	display_name: "Auburn"
	abbreviation: "AUB"
	primary_color {
		red: 3
		green: 36
		blue: 77
	}
	secondary_color: {
		red: 241
		green: 242
		blue: 243
	}
}
Team { 
	id: 161
	location: "Fairleigh Dickinson"
	name: "Knights"
	display_name: "Fair Dick"
	abbreviation: "FDU"
	primary_color {
		red: 0
		green: 68
		blue: 156
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 150
	location: "Duke"
	name: "Blue Devils"
	display_name: "Duke"
	abbreviation: "DUKE"
	primary_color {
		red: 0
		green: 26
		blue: 87
	}
	secondary_color: {
		red: 241
		green: 242
		blue: 243
	}
}
Team { 
	id: 25
	location: "California"
	name: "Golden Bears"
	display_name: "California"
	abbreviation: "CAL"
	primary_color {
		red: 3
		green: 21
		blue: 34
	}
	secondary_color: {
		red: 255
		green: 196
		blue: 35
	}
}
Team { 
	id: 2351
	location: "Loyola Marymount"
	name: "Lions"
	display_name: "Loyola M"
	abbreviation: "LMU"
	primary_color {
		red: 136
		green: 0
		blue: 41
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2193
	location: "East Tennessee State"
	name: "Buccaneers"
	display_name: "ETSU"
	abbreviation: "ETSU"
	primary_color {
		red: 0
		green: 45
		blue: 97
	}
	secondary_color: {
		red: 255
		green: 196
		blue: 35
	}
}
Team { 
	id: 265
	location: "Washington State"
	name: "Cougars"
	display_name: "Wash St"
	abbreviation: "WSU"
	primary_color {
		red: 148
		green: 2
		blue: 42
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 135
	location: "Minnesota"
	name: "Golden Gophers"
	display_name: "Minnesota"
	abbreviation: "MINN"
	primary_color {
		red: 152
		green: 26
		blue: 49
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 305
	location: "DePaul"
	name: "Blue Demons"
	display_name: "DePaul"
	abbreviation: "DEP"
	primary_color {
		red: 45
		green: 100
		blue: 156
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 227
	location: "Rhode Island"
	name: "Rams"
	display_name: "Rhode Isl"
	abbreviation: "URI"
	primary_color {
		red: 9
		green: 31
		blue: 63
	}
	secondary_color: {
		red: 90
		green: 179
		blue: 232
	}
}
Team { 
	id: 2217
	location: "Fairfield"
	name: "Stags"
	display_name: "Fairfield"
	abbreviation: "FAIR"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 235
		green: 235
		blue: 235
	}
}
Team { 
	id: 167
	location: "New Mexico"
	name: "Lobos"
	display_name: "New Mexico"
	abbreviation: "UNM"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 164
	location: "Rutgers"
	name: "Scarlet Knights"
	display_name: "Rutgers"
	abbreviation: "RUTG"
	primary_color {
		red: 210
		green: 16
		blue: 52
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 158
	location: "Nebraska"
	name: "Cornhuskers"
	display_name: "Nebraska"
	abbreviation: "NEB"
	primary_color {
		red: 242
		green: 0
		blue: 23
	}
	secondary_color: {
		red: 245
		green: 241
		blue: 231
	}
}
Team { 
	id: 77
	location: "Northwestern"
	name: "Wildcats"
	display_name: "N Western"
	abbreviation: "NW"
	primary_color {
		red: 55
		green: 34
		blue: 134
	}
	secondary_color: {
		red: 214
		green: 202
		blue: 193
	}
}
Team { 
	id: 127
	location: "Michigan State"
	name: "Spartans"
	display_name: "Michigan St"
	abbreviation: "MSU"
	primary_color {
		red: 24
		green: 69
		blue: 59
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 236
	location: "Chattanooga"
	name: "Mocs"
	display_name: "Chattanooga"
	abbreviation: "UTC"
	primary_color {
		red: 0
		green: 56
		blue: 107
	}
	secondary_color: {
		red: 220
		green: 167
		blue: 29
	}
}
Team { 
	id: 163
	location: "Princeton"
	name: "Tigers"
	display_name: "Princeton"
	abbreviation: "PRIN"
	primary_color {
		red: 255
		green: 148
		blue: 8
	}
	secondary_color: {
		red: 8
		green: 8
		blue: 8
	}
}
Team { 
	id: 275
	location: "Wisconsin"
	name: "Badgers"
	display_name: "Wisconsin"
	abbreviation: "WISC"
	primary_color {
		red: 160
		green: 0
		blue: 2
	}
	secondary_color: {
		red: 247
		green: 247
		blue: 247
	}
}
Team { 
	id: 228
	location: "Clemson"
	name: "Tigers"
	display_name: "Clemson"
	abbreviation: "CLEM"
	primary_color {
		red: 246
		green: 103
		blue: 51
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 264
	location: "Washington"
	name: "Huskies"
	display_name: "Washington"
	abbreviation: "WASH"
	primary_color {
		red: 43
		green: 47
		blue: 100
	}
	secondary_color: {
		red: 232
		green: 227
		blue: 211
	}
}
Team { 
	id: 9
	location: "Arizona State"
	name: "Sun Devils"
	display_name: "Arizona St"
	abbreviation: "ASU"
	primary_color {
		red: 148
		green: 33
		blue: 57
	}
	secondary_color: {
		red: 241
		green: 242
		blue: 243
	}
}
Team { 
	id: 232
	location: "Charleston"
	name: "Cougars"
	display_name: "Charleston"
	abbreviation: "COFC"
	primary_color {
		red: 156
		green: 132
		blue: 86
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2509
	location: "Purdue"
	name: "Boilermakers"
	display_name: "Purdue"
	abbreviation: "PUR"
	primary_color {
		red: 206
		green: 184
		blue: 136
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 66
	location: "Iowa State"
	name: "Cyclones"
	display_name: "Iowa State"
	abbreviation: "ISU"
	primary_color {
		red: 102
		green: 0
		blue: 21
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 339
	location: "Evansville"
	name: "Purple Aces"
	display_name: "Evansville"
	abbreviation: "EVAN"
	primary_color {
		red: 102
		green: 51
		blue: 153
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2344
	location: "Longwood"
	name: "Lancers"
	display_name: "Longwood"
	abbreviation: "LONG"
	primary_color {
		red: 0
		green: 50
		blue: 115
	}
	secondary_color: {
		red: 158
		green: 162
		blue: 163
	}
}
Team { 
	id: 52
	location: "Florida State"
	name: "Seminoles"
	display_name: "Florida St"
	abbreviation: "FSU"
	primary_color {
		red: 120
		green: 47
		blue: 64
	}
	secondary_color: {
		red: 206
		green: 184
		blue: 136
	}
}
Team { 
	id: 242
	location: "Rice"
	name: "Owls"
	display_name: "Rice"
	abbreviation: "RICE"
	primary_color {
		red: 0
		green: 61
		blue: 125
	}
	secondary_color: {
		red: 209
		green: 213
		blue: 216
	}
}
Team { 
	id: 44
	location: "American"
	name: "Eagles"
	display_name: "American"
	abbreviation: "AMER"
	primary_color {
		red: 196
		green: 17
		blue: 48
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2016
	location: "Alcorn State"
	name: "Braves"
	display_name: "Alcorn St"
	abbreviation: "ALCN"
	primary_color {
		red: 75
		green: 0
		blue: 88
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2272
	location: "High Point"
	name: "Panthers"
	display_name: "High Point"
	abbreviation: "HP"
	primary_color {
		red: 176
		green: 183
		blue: 188
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 251
	location: "Texas"
	name: "Longhorns"
	display_name: "Texas"
	abbreviation: "TEX"
	primary_color {
		red: 238
		green: 117
		blue: 36
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 254
	location: "Utah"
	name: "Utes"
	display_name: "Utah"
	abbreviation: "UTAH"
	primary_color {
		red: 137
		green: 0
		blue: 18
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2674
	location: "Valparaiso"
	name: "Crusaders"
	display_name: "Valparaiso"
	abbreviation: "VAL"
	primary_color {
		red: 121
		green: 69
		blue: 0
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 107
	location: "Holy Cross"
	name: "Crusaders"
	display_name: "Holy Cross"
	abbreviation: "HC"
	primary_color {
		red: 10
		green: 10
		blue: 10
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 526
	location: "Florida Gulf Coast"
	name: "Eagles"
	display_name: "FGCU"
	abbreviation: "FGCU"
	primary_color {
		red: 0
		green: 136
		blue: 90
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 159
	location: "Dartmouth"
	name: "Big Green"
	display_name: "Dartmouth"
	abbreviation: "DART"
	primary_color {
		red: 0
		green: 87
		blue: 48
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 311
	location: "Maine"
	name: "Black Bears"
	display_name: "Maine"
	abbreviation: "ME"
	primary_color {
		red: 18
		green: 125
		blue: 190
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 149
	location: "Montana"
	name: "Grizzlies"
	display_name: "Montana"
	abbreviation: "MONT"
	primary_color {
		red: 117
		green: 29
		blue: 74
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 333
	location: "Alabama"
	name: "Crimson Tide"
	display_name: "Alabama"
	abbreviation: "ALA"
	primary_color {
		red: 105
		green: 0
		blue: 20
	}
	secondary_color: {
		red: 241
		green: 242
		blue: 243
	}
}
Team { 
	id: 2309
	location: "Kent State"
	name: "Golden Flashes"
	display_name: "Kent State"
	abbreviation: "KENT"
	primary_color {
		red: 0
		green: 36
		blue: 69
	}
	secondary_color: {
		red: 240
		green: 181
		blue: 16
	}
}
Team { 
	id: 2172
	location: "Denver"
	name: "Pioneers"
	display_name: "Denver"
	abbreviation: "DEN"
	primary_color {
		red: 156
		green: 20
		blue: 61
	}
	secondary_color: {
		red: 214
		green: 186
		blue: 116
	}
}
Team { 
	id: 94
	location: "Northern Kentucky"
	name: "Norse"
	display_name: "N Kentucky"
	abbreviation: "NKU"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 234
		green: 182
		blue: 33
	}
}
Team { 
	id: 202
	location: "Tulsa"
	name: "Golden Hurricane"
	display_name: "Tulsa"
	abbreviation: "TLSA"
	primary_color {
		red: 0
		green: 67
		blue: 113
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 301
	location: "San Diego"
	name: "Toreros"
	display_name: "San Diego"
	abbreviation: "USD"
	primary_color {
		red: 47
		green: 153
		blue: 212
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 328
	location: "Utah State"
	name: "Aggies"
	display_name: "Utah State"
	abbreviation: "USU"
	primary_color {
		red: 0
		green: 50
		blue: 99
	}
	secondary_color: {
		red: 148
		green: 156
		blue: 161
	}
}
Team { 
	id: 2636
	location: "UTSA"
	name: "Roadrunners"
	display_name: "Texas SA"
	abbreviation: "UTSA"
	primary_color {
		red: 0
		green: 42
		blue: 92
	}
	secondary_color: {
		red: 244
		green: 115
		blue: 33
	}
}
Team { 
	id: 156
	location: "Creighton"
	name: "Bluejays"
	display_name: "Creighton"
	abbreviation: "CREI"
	primary_color {
		red: 19
		green: 41
		blue: 158
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2166
	location: "Davidson"
	name: "Wildcats"
	display_name: "Davidson"
	abbreviation: "DAV"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 229
		green: 24
		blue: 55
	}
}
Team { 
	id: 36
	location: "Colorado State"
	name: "Rams"
	display_name: "Colorado St"
	abbreviation: "CSU"
	primary_color {
		red: 0
		green: 69
		blue: 55
	}
	secondary_color: {
		red: 255
		green: 196
		blue: 37
	}
}
Team { 
	id: 55
	location: "Jacksonville State"
	name: "Gamecocks"
	display_name: "Jack St"
	abbreviation: "JVST"
	primary_color {
		red: 181
		green: 5
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2296
	location: "Jackson State"
	name: "Tigers"
	display_name: "Jackson St"
	abbreviation: "JKST"
	primary_color {
		red: 18
		green: 50
		blue: 151
	}
	secondary_color: {
		red: 181
		green: 183
		blue: 186
	}
}
Team { 
	id: 21
	location: "San Diego State"
	name: "Aztecs"
	display_name: "San D St"
	abbreviation: "SDSU"
	primary_color {
		red: 191
		green: 44
		blue: 55
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2006
	location: "Akron"
	name: "Zips"
	display_name: "Akron"
	abbreviation: "AKR"
	primary_color {
		red: 0
		green: 40
		blue: 94
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2084
	location: "Buffalo"
	name: "Bulls"
	display_name: "Buffalo"
	abbreviation: "BUFF"
	primary_color {
		red: 4
		green: 26
		blue: 155
	}
	secondary_color: {
		red: 235
		green: 235
		blue: 235
	}
}
Team { 
	id: 2572
	location: "Southern Miss"
	name: "S Miss"
	display_name: "G Eagles"
	abbreviation: "USM"
	primary_color {
		red: 255
		green: 170
		blue: 60
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2390
	location: "Miami"
	name: "Hurricanes"
	display_name: "Miami"
	abbreviation: "MIA"
	primary_color {
		red: 0
		green: 67
		blue: 37
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 130
	location: "Michigan"
	name: "Wolverines"
	display_name: "Michigan"
	abbreviation: "MICH"
	primary_color {
		red: 0
		green: 39
		blue: 76
	}
	secondary_color: {
		red: 255
		green: 203
		blue: 5
	}
}
Team { 
	id: 2050
	location: "Ball State"
	name: "Cardinals"
	display_name: "Ball State"
	abbreviation: "BALL"
	primary_color {
		red: 218
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 46
	location: "Georgetown"
	name: "Hoyas"
	display_name: "Georgetown"
	abbreviation: "GTWN"
	primary_color {
		red: 17
		green: 14
		blue: 66
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 47
	location: "Howard"
	name: "Bison"
	display_name: "Howard"
	abbreviation: "HOW"
	primary_color {
		red: 158
		green: 11
		blue: 14
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 38
	location: "Colorado"
	name: "Buffaloes"
	display_name: "Colorado"
	abbreviation: "COLO"
	primary_color {
		red: 209
		green: 197
		blue: 126
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 326
	location: "Texas State"
	name: "Bobcats"
	display_name: "Texas State"
	abbreviation: "TXST"
	primary_color {
		red: 78
		green: 23
		blue: 25
	}
	secondary_color: {
		red: 180
		green: 151
		blue: 90
	}
}
Team { 
	id: 198
	location: "Oral Roberts"
	name: "Golden Eagles"
	display_name: "Oral R"
	abbreviation: "ORU"
	primary_color {
		red: 0
		green: 41
		blue: 85
	}
	secondary_color: {
		red: 204
		green: 180
		blue: 140
	}
}
Team { 
	id: 231
	location: "Furman"
	name: "Paladins"
	display_name: "Furman"
	abbreviation: "FUR"
	primary_color {
		red: 74
		green: 33
		blue: 132
	}
	secondary_color: {
		red: 144
		green: 144
		blue: 144
	}
}
Team { 
	id: 322
	location: "Lafayette"
	name: "Leopards"
	display_name: "Lafayette"
	abbreviation: "LAF"
	primary_color {
		red: 121
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 165
		green: 148
		blue: 116
	}
}
Team { 
	id: 302
	location: "UC Davis"
	name: "Aggies"
	display_name: "UC Davis"
	abbreviation: "UCD"
	primary_color {
		red: 24
		green: 53
		blue: 99
	}
	secondary_color: {
		red: 188
		green: 147
		blue: 5
	}
}
Team { 
	id: 62
	location: "Hawai'i"
	name: "Rainbow Warriors"
	display_name: "Hawai'i"
	abbreviation: "HAW"
	primary_color {
		red: 0
		green: 52
		blue: 32
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2169
	location: "Delaware St"
	name: "Hornets"
	display_name: "Delaware St"
	abbreviation: "DSU"
	primary_color {
		red: 255
		green: 54
		blue: 48
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2638
	location: "UTEP"
	name: "Miners"
	display_name: "Texas EP"
	abbreviation: "UTEP"
	primary_color {
		red: 255
		green: 130
		blue: 0
	}
	secondary_color: {
		red: 4
		green: 30
		blue: 66
	}
}
Team { 
	id: 2325
	location: "La Salle"
	name: "Explorers"
	display_name: "La Salle"
	abbreviation: "LAS"
	primary_color {
		red: 0
		green: 0
		blue: 99
	}
	secondary_color: {
		red: 254
		green: 202
		blue: 38
	}
}
Team { 
	id: 250
	location: "UT Arlington"
	name: "Mavericks"
	display_name: "UT A"
	abbreviation: "UTA"
	primary_color {
		red: 0
		green: 75
		blue: 124
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 189
	location: "Bowling Green"
	name: "Falcons"
	display_name: "Bowling G"
	abbreviation: "BGSU"
	primary_color {
		red: 43
		green: 16
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 349
	location: "Army"
	name: "Black Knights"
	display_name: "Army"
	abbreviation: "ARMY"
	primary_color {
		red: 206
		green: 156
		blue: 0
	}
	secondary_color: {
		red: 35
		green: 31
		blue: 32
	}
}
Team { 
	id: 2029
	location: "Arkansas-Pine Bluff"
	name: "Golden Lions"
	display_name: "Ark-Pine"
	abbreviation: "UAPB"
	primary_color {
		red: 224
		green: 170
		blue: 15
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2275
	location: "Hofstra"
	name: "Pride"
	display_name: "Hofstra"
	abbreviation: "HOF"
	primary_color {
		red: 0
		green: 51
		blue: 124
	}
	secondary_color: {
		red: 246
		green: 201
		blue: 52
	}
}
Team { 
	id: 218
	location: "Temple"
	name: "Owls"
	display_name: "Temple"
	abbreviation: "TEM"
	primary_color {
		red: 168
		green: 5
		blue: 50
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 85
	location: "IUPUI"
	name: "Jaguars"
	display_name: "IUPUI"
	abbreviation: "IUPU"
	primary_color {
		red: 168
		green: 31
		blue: 48
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 152
	location: "NC State"
	name: "Wolfpack"
	display_name: "NC State"
	abbreviation: "NCST"
	primary_color {
		red: 239
		green: 18
		blue: 22
	}
	secondary_color: {
		red: 35
		green: 31
		blue: 32
	}
}
Team { 
	id: 154
	location: "Wake Forest"
	name: "Demon Deacons"
	display_name: "Wake Forest"
	abbreviation: "WAKE"
	primary_color {
		red: 158
		green: 126
		blue: 56
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 27
	location: "UC Riverside"
	name: "Highlanders"
	display_name: "UC River"
	abbreviation: "UCR"
	primary_color {
		red: 20
		green: 35
		blue: 79
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 315
	location: "Niagara"
	name: "Purple Eagles"
	display_name: "Niagara"
	abbreviation: "NIAG"
	primary_color {
		red: 105
		green: 32
		blue: 126
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 2253
	location: "Grand Canyon"
	name: "Antelopes"
	display_name: "G Canyon"
	abbreviation: "GCU"
	primary_color {
		red: 82
		green: 35
		blue: 152
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 2026
	location: "Appalachian State"
	name: "Mountaineers"
	display_name: "App St"
	abbreviation: "APP"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 205
		blue: 0
	}
}
Team { 
	id: 278
	location: "Fresno State"
	name: "Bulldogs"
	display_name: "Fresno St"
	abbreviation: "FRES"
	primary_color {
		red: 196
		green: 18
		blue: 48
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 314
	location: "Iona"
	name: "Gaels"
	display_name: "Iona"
	abbreviation: "IONA"
	primary_color {
		red: 140
		green: 0
		blue: 26
	}
	secondary_color: {
		red: 246
		green: 167
		blue: 4
	}
}
Team { 
	id: 108
	location: "Harvard"
	name: "Crimson"
	display_name: "Harvard"
	abbreviation: "HARV"
	primary_color {
		red: 153
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 219
		green: 219
		blue: 219
	}
}
Team { 
	id: 151
	location: "East Carolina"
	name: "Pirates"
	display_name: "E Carolina"
	abbreviation: "ECU"
	primary_color {
		red: 75
		green: 24
		blue: 105
	}
	secondary_color: {
		red: 240
		green: 144
		blue: 123
	}
}
Team { 
	id: 111
	location: "Northeastern"
	name: "Huskies"
	display_name: "NE"
	abbreviation: "NE"
	primary_color {
		red: 204
		green: 0
		blue: 1
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2244
	location: "George Mason"
	name: "Patriots"
	display_name: "George M"
	abbreviation: "GMU"
	primary_color {
		red: 1
		green: 102
		blue: 0
	}
	secondary_color: {
		red: 236
		green: 176
		blue: 16
	}
}
Team { 
	id: 119
	location: "Towson"
	name: "Tigers"
	display_name: "Towson"
	abbreviation: "TOW"
	primary_color {
		red: 255
		green: 194
		blue: 41
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 304
	location: "Idaho State"
	name: "Bengals"
	display_name: "Idaho State"
	abbreviation: "IDST"
	primary_color {
		red: 239
		green: 140
		blue: 0
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 98
	location: "Western Kentucky"
	name: "Hilltoppers"
	display_name: "Western KY"
	abbreviation: "WKU"
	primary_color {
		red: 243
		green: 32
		blue: 38
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 324
	location: "Coastal Carolina"
	name: "Chanticleers"
	display_name: "C. Carolina"
	abbreviation: "CCAR"
	primary_color {
		red: 0
		green: 112
		blue: 115
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2184
	location: "Duquesne"
	name: "Dukes"
	display_name: "Duquesne"
	abbreviation: "DUQ"
	primary_color {
		red: 0
		green: 45
		blue: 98
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 195
	location: "Ohio"
	name: "Bobcats"
	display_name: "Ohio"
	abbreviation: "OHIO"
	primary_color {
		red: 41
		green: 90
		blue: 41
	}
	secondary_color: {
		red: 228
		green: 187
		blue: 133
	}
}
Team { 
	id: 239
	location: "Baylor"
	name: "Bears"
	display_name: "Baylor"
	abbreviation: "BAY"
	primary_color {
		red: 0
		green: 72
		blue: 52
	}
	secondary_color: {
		red: 255
		green: 184
		blue: 28
	}
}
Team { 
	id: 357
	location: "Texas A&M-CC"
	name: "Islanders"
	display_name: "Tex A&M CC"
	abbreviation: "AMCC"
	primary_color {
		red: 0
		green: 99
		blue: 156
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 288
	location: "Lipscomb"
	name: "Bisons"
	display_name: "Lipscomb"
	abbreviation: "LIP"
	primary_color {
		red: 32
		green: 54
		blue: 108
	}
	secondary_color: {
		red: 246
		green: 183
		blue: 52
	}
}
Team { 
	id: 257
	location: "Richmond"
	name: "Spiders"
	display_name: "Richmond"
	abbreviation: "RICH"
	primary_color {
		red: 158
		green: 7
		blue: 18
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 139
	location: "Saint Louis"
	name: "Billikens"
	display_name: "Saint Louis"
	abbreviation: "SLU"
	primary_color {
		red: 0
		green: 83
		blue: 156
	}
	secondary_color: {
		red: 235
		green: 235
		blue: 235
	}
}
Team { 
	id: 93
	location: "Murray State"
	name: "Racers"
	display_name: "Murray St"
	abbreviation: "MUR"
	primary_color {
		red: 0
		green: 33
		blue: 72
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 48
	location: "Delaware"
	name: "Blue Hens"
	display_name: "Delaware"
	abbreviation: "DEL"
	primary_color {
		red: 3
		green: 53
		blue: 148
	}
	secondary_color: {
		red: 232
		green: 206
		blue: 49
	}
}
Team { 
	id: 2335
	location: "Liberty"
	name: "Flames"
	display_name: "Liberty"
	abbreviation: "LIB"
	primary_color {
		red: 7
		green: 23
		blue: 64
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 104
	location: "Boston Univ."
	name: "Terriers"
	display_name: "Boston U"
	abbreviation: "BU"
	primary_color {
		red: 204
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 325
	location: "Cleveland State"
	name: "Vikings"
	display_name: "C St"
	abbreviation: "CLEV"
	primary_color {
		red: 0
		green: 102
		blue: 51
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2210
	location: "Elon"
	name: "Phoenix"
	display_name: "Elon"
	abbreviation: "ELON"
	primary_color {
		red: 2
		green: 3
		blue: 3
	}
	secondary_color: {
		red: 181
		green: 154
		blue: 87
	}
}
Team { 
	id: 292
	location: "UT Rio Grande Valley"
	name: "Vaqueros"
	display_name: "UT RG"
	abbreviation: "UTRGV"
	primary_color {
		red: 220
		green: 96
		blue: 0
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2226
	location: "Florida Atlantic"
	name: "Owls"
	display_name: "FAU"
	abbreviation: "FAU"
	primary_color {
		red: 0
		green: 75
		blue: 133
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2011
	location: "Alabama State"
	name: "Hornets"
	display_name: "Alabama St"
	abbreviation: "ALST"
	primary_color {
		red: 233
		green: 169
		blue: 0
	}
	secondary_color: {
		red: 10
		green: 10
		blue: 10
	}
}
Team { 
	id: 299
	location: "Long Beach State"
	name: "Beach"
	display_name: "LB State"
	abbreviation: "LBSU"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 241
		green: 242
		blue: 243
	}
}
Team { 
	id: 2348
	location: "Louisiana Tech"
	name: "Bulldogs"
	display_name: "L Tech"
	abbreviation: "LT"
	primary_color {
		red: 0
		green: 45
		blue: 101
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 338
	location: "Kennesaw State"
	name: "Owls"
	display_name: "Kennesaw St"
	abbreviation: "KENN"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 253
		green: 187
		blue: 48
	}
}
Team { 
	id: 252
	location: "BYU"
	name: "Cougars"
	display_name: "BYU"
	abbreviation: "BYU"
	primary_color {
		red: 0
		green: 30
		blue: 76
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2261
	location: "Hampton"
	name: "Pirates"
	display_name: "Hampton"
	abbreviation: "HAMP"
	primary_color {
		red: 0
		green: 103
		blue: 172
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2116
	location: "UCF"
	name: "Knights"
	display_name: "UCF"
	abbreviation: "UCF"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 222
	location: "Villanova"
	name: "Wildcats"
	display_name: "Villanova"
	abbreviation: "VILL"
	primary_color {
		red: 18
		green: 61
		blue: 124
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 5
	location: "UAB"
	name: "Blazers"
	display_name: "UAB"
	abbreviation: "UAB"
	primary_color {
		red: 5
		green: 67
		blue: 56
	}
	secondary_color: {
		red: 255
		green: 200
		blue: 69
	}
}
Team { 
	id: 235
	location: "Memphis"
	name: "Tigers"
	display_name: "Memphis"
	abbreviation: "MEM"
	primary_color {
		red: 0
		green: 36
		blue: 71
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 300
	location: "UC Irvine"
	name: "Anteaters"
	display_name: "UC Irvine"
	abbreviation: "UCI"
	primary_color {
		red: 0
		green: 43
		blue: 92
	}
	secondary_color: {
		red: 254
		green: 197
		blue: 46
	}
}
Team { 
	id: 71
	location: "Bradley"
	name: "Braves"
	display_name: "Bradley"
	abbreviation: "BRAD"
	primary_color {
		red: 183
		green: 0
		blue: 2
	}
	secondary_color: {
		red: 192
		green: 192
		blue: 192
	}
}
Team { 
	id: 68
	location: "Boise State"
	name: "Broncos"
	display_name: "Boise State"
	abbreviation: "BSU"
	primary_color {
		red: 9
		green: 52
		blue: 122
	}
	secondary_color: {
		red: 216
		green: 217
		blue: 218
	}
}
Team { 
	id: 183
	location: "Syracuse"
	name: "Orange"
	display_name: "Syracuse"
	abbreviation: "SYR"
	primary_color {
		red: 243
		green: 115
		blue: 33
	}
	secondary_color: {
		red: 13
		green: 29
		blue: 55
	}
}
Team { 
	id: 2198
	location: "Eastern Kentucky"
	name: "Colonels"
	display_name: "E Kentucky"
	abbreviation: "EKU"
	primary_color {
		red: 102
		green: 8
		blue: 25
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 26
	location: "UCLA"
	name: "Bruins"
	display_name: "UCLA"
	abbreviation: "UCLA"
	primary_color {
		red: 0
		green: 92
		blue: 142
	}
	secondary_color: {
		red: 255
		green: 199
		blue: 44
	}
}
Team { 
	id: 259
	location: "Virginia Tech"
	name: "Hokies"
	display_name: "V Tech"
	abbreviation: "VT"
	primary_color {
		red: 116
		green: 35
		blue: 45
	}
	secondary_color: {
		red: 194
		green: 193
		blue: 186
	}
}
Team { 
	id: 2199
	location: "Eastern Michigan"
	name: "Eagles"
	display_name: "E Michigan"
	abbreviation: "EMU"
	primary_color {
		red: 0
		green: 51
		blue: 27
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 42
	location: "Hartford"
	name: "Hawks"
	display_name: "Hartford"
	abbreviation: "HART"
	primary_color {
		red: 214
		green: 0
		blue: 8
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2349
	location: "UMass Lowell"
	name: "River Hawks"
	display_name: "UMass L"
	abbreviation: "UML"
	primary_color {
		red: 0
		green: 82
		blue: 156
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2181
	location: "Drake"
	name: "Bulldogs"
	display_name: "Drake"
	abbreviation: "DRKE"
	primary_color {
		red: 0
		green: 68
		blue: 119
	}
	secondary_color: {
		red: 192
		green: 192
		blue: 192
	}
}
Team { 
	id: 12
	location: "Arizona"
	name: "Wildcats"
	display_name: "Arizona"
	abbreviation: "ARIZ"
	primary_color {
		red: 0
		green: 36
		blue: 73
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 219
	location: "Pennsylvania"
	name: "Quakers"
	display_name: "Penn"
	abbreviation: "PENN"
	primary_color {
		red: 8
		green: 42
		blue: 116
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2010
	location: "Alabama A&M"
	name: "Bulldogs"
	display_name: "Alabama A&M"
	abbreviation: "AAMU"
	primary_color {
		red: 121
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2350
	location: "Loyola Chicago"
	name: "Ramblers"
	display_name: "Loyola C"
	abbreviation: "LUC"
	primary_color {
		red: 157
		green: 18
		blue: 68
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 84
	location: "Indiana"
	name: "Hoosiers"
	display_name: "Indiana"
	abbreviation: "IU"
	primary_color {
		red: 125
		green: 17
		blue: 12
	}
	secondary_color: {
		red: 238
		green: 237
		blue: 235
	}
}
Team { 
	id: 2247
	location: "Georgia State"
	name: "Panthers"
	display_name: "Georgia St"
	abbreviation: "GAST"
	primary_color {
		red: 30
		green: 83
		blue: 154
	}
	secondary_color: {
		red: 235
		green: 235
		blue: 235
	}
}
Team { 
	id: 113
	location: "UMass"
	name: "Minutemen"
	display_name: "UMass"
	abbreviation: "MASS"
	primary_color {
		red: 136
		green: 0
		blue: 7
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2277
	location: "Houston Baptist"
	name: "Huskies"
	display_name: "H Baptist"
	abbreviation: "HBU"
	primary_color {
		red: 0
		green: 83
		blue: 156
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 213
	location: "Penn State"
	name: "Nittany Lions"
	display_name: "Penn State"
	abbreviation: "PSU"
	primary_color {
		red: 0
		green: 38
		blue: 93
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 24
	location: "Stanford"
	name: "Cardinal"
	display_name: "Stanford"
	abbreviation: "STAN"
	primary_color {
		red: 168
		green: 5
		blue: 50
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 356
	location: "Illinois"
	name: "Fighting Illini"
	display_name: "Illinois"
	abbreviation: "ILL"
	primary_color {
		red: 247
		green: 115
		blue: 41
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 2046
	location: "Austin Peay"
	name: "Governors"
	display_name: "Austin Peay"
	abbreviation: "APSU"
	primary_color {
		red: 142
		green: 11
		blue: 11
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2005
	location: "Air Force"
	name: "Falcons"
	display_name: "Air Force"
	abbreviation: "AFA"
	primary_color {
		red: 0
		green: 74
		blue: 123
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 160
	location: "New Hampshire"
	name: "Wildcats"
	display_name: "New Hamp"
	abbreviation: "UNH"
	primary_color {
		red: 0
		green: 73
		blue: 144
	}
	secondary_color: {
		red: 195
		green: 196
		blue: 198
	}
}
Team { 
	id: 179
	location: "St. Bonaventure"
	name: "Bonnies"
	display_name: "St. Bon"
	abbreviation: "SBU"
	primary_color {
		red: 112
		green: 38
		blue: 29
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 56
	location: "Stetson"
	name: "Hatters"
	display_name: "Stetson"
	abbreviation: "STET"
	primary_color {
		red: 10
		green: 86
		blue: 64
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 57
	location: "Florida"
	name: "Gators"
	display_name: "Florida"
	abbreviation: "FLA"
	primary_color {
		red: 0
		green: 33
		blue: 165
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2000
	location: "Abilene Christian"
	name: "Wildcats"
	display_name: "Abil Christ"
	abbreviation: "ACU"
	primary_color {
		red: 78
		green: 38
		blue: 131
	}
	secondary_color: {
		red: 235
		green: 235
		blue: 235
	}
}
Team { 
	id: 350
	location: "UNC Wilmington"
	name: "Seahawks"
	display_name: "UNC Wilm"
	abbreviation: "UNCW"
	primary_color {
		red: 29
		green: 47
		blue: 104
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2097
	location: "Campbell"
	name: "Fighting Camels"
	display_name: "Campbell"
	abbreviation: "CAM"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2182
	location: "Drexel"
	name: "Dragons"
	display_name: "Drexel"
	abbreviation: "DREX"
	primary_color {
		red: 2
		green: 2
		blue: 96
	}
	secondary_color: {
		red: 255
		green: 214
		blue: 90
	}
}
Team { 
	id: 59
	location: "Georgia Tech"
	name: "Yellow Jackets"
	display_name: "G Tech"
	abbreviation: "GT"
	primary_color {
		red: 0
		green: 34
		blue: 62
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 153
	location: "North Carolina"
	name: "Tar Heels"
	display_name: "N Carolina"
	abbreviation: "UNC"
	primary_color {
		red: 153
		green: 191
		blue: 229
	}
	secondary_color: {
		red: 19
		green: 41
		blue: 75
	}
}
Team { 
	id: 2229
	location: "Florida Int'l"
	name: "Panthers"
	display_name: "FIU"
	abbreviation: "FIU"
	primary_color {
		red: 9
		green: 23
		blue: 49
	}
	secondary_color: {
		red: 197
		green: 150
		blue: 12
	}
}
Team { 
	id: 258
	location: "Virginia"
	name: "Cavaliers"
	display_name: "Virginia"
	abbreviation: "UVA"
	primary_color {
		red: 248
		green: 76
		blue: 30
	}
	secondary_color: {
		red: 36
		green: 46
		blue: 74
	}
}
Team { 
	id: 270
	location: "Milwaukee"
	name: "Panthers"
	display_name: "Milwaukee"
	abbreviation: "MILW"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 194
		blue: 14
	}
}
Team { 
	id: 2117
	location: "Central Michigan"
	name: "Chippewas"
	display_name: "Cent Mich"
	abbreviation: "CMU"
	primary_color {
		red: 106
		green: 0
		blue: 50
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 147
	location: "Montana State"
	name: "Bobcats"
	display_name: "Montana St"
	abbreviation: "MTST"
	primary_color {
		red: 0
		green: 56
		blue: 117
	}
	secondary_color: {
		red: 191
		green: 150
		blue: 92
	}
}
Team { 
	id: 295
	location: "Old Dominion"
	name: "Monarchs"
	display_name: "Old D"
	abbreviation: "ODU"
	primary_color {
		red: 0
		green: 80
		blue: 125
	}
	secondary_color: {
		red: 161
		green: 210
		blue: 241
	}
}
Team { 
	id: 193
	location: "Miami (OH)"
	name: "Redhawks"
	display_name: "Miami (OH)"
	abbreviation: "M-OH"
	primary_color {
		red: 164
		green: 0
		blue: 12
	}
	secondary_color: {
		red: 240
		green: 240
		blue: 240
	}
}
Team { 
	id: 79
	location: "Southern Illinois"
	name: "Salukis"
	display_name: "So Illinois"
	abbreviation: "SIU"
	primary_color {
		red: 133
		green: 40
		blue: 61
	}
	secondary_color: {
		red: 194
		green: 195
		blue: 192
	}
}
Team { 
	id: 245
	location: "Texas A&M"
	name: "Aggies"
	display_name: "Texas A&M"
	abbreviation: "TA&M"
	primary_color {
		red: 92
		green: 0
		blue: 37
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2329
	location: "Lehigh"
	name: "Mountain Hawks"
	display_name: "Lehigh"
	abbreviation: "LEH"
	primary_color {
		red: 108
		green: 43
		blue: 42
	}
	secondary_color: {
		red: 182
		green: 158
		blue: 112
	}
}
Team { 
	id: 2168
	location: "Dayton"
	name: "Flyers"
	display_name: "Dayton"
	abbreviation: "DAY"
	primary_color {
		red: 0
		green: 75
		blue: 141
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 256
	location: "James Madison"
	name: "Dukes"
	display_name: "James M"
	abbreviation: "JMU"
	primary_color {
		red: 69
		green: 0
		blue: 132
	}
	secondary_color: {
		red: 203
		green: 183
		blue: 120
	}
}
Team { 
	id: 294
	location: "Jacksonville"
	name: "Dolphins"
	display_name: "Jack"
	abbreviation: "JAX"
	primary_color {
		red: 0
		green: 82
		blue: 62
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 248
	location: "Houston"
	name: "Cougars"
	display_name: "Houston"
	abbreviation: "HOU"
	primary_color {
		red: 201
		green: 8
		blue: 34
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 344
	location: "Mississippi State"
	name: "Bulldogs"
	display_name: "Miss St"
	abbreviation: "MSST"
	primary_color {
		red: 118
		green: 33
		blue: 35
	}
	secondary_color: {
		red: 200
		green: 200
		blue: 200
	}
}
Team { 
	id: 204
	location: "Oregon State"
	name: "Beavers"
	display_name: "Oregon St"
	abbreviation: "ORST"
	primary_color {
		red: 195
		green: 69
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2099
	location: "Canisius"
	name: "Golden Griffins"
	display_name: "Canisius"
	abbreviation: "CAN"
	primary_color {
		red: 0
		green: 74
		blue: 129
	}
	secondary_color: {
		red: 221
		green: 165
		blue: 15
	}
}
Team { 
	id: 221
	location: "Pittsburgh"
	name: "Panthers"
	display_name: "Pittsburgh"
	abbreviation: "PITT"
	primary_color {
		red: 0
		green: 50
		blue: 99
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2174
	location: "Detroit Mercy"
	name: "Titans"
	display_name: "Detroit M"
	abbreviation: "DET"
	primary_color {
		red: 22
		green: 91
		blue: 158
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 2320
	location: "Lamar"
	name: "Cardinals"
	display_name: "Lamar"
	abbreviation: "LAM"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 235
		green: 235
		blue: 235
	}
}
Team { 
	id: 2305
	location: "Kansas"
	name: "Jayhawks"
	display_name: "Kansas"
	abbreviation: "KU"
	primary_color {
		red: 0
		green: 34
		blue: 180
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 171
	location: "Columbia"
	name: "Lions"
	display_name: "Columbia"
	abbreviation: "CLMB"
	primary_color {
		red: 23
		green: 71
		blue: 133
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
