Team { 
	id: 2
	location: "Boston"
	name: "Celtics"
	display_name: "Celtics"
	abbreviation: "BOS"
	primary_color {
		red: 0
		green: 101
		blue: 50
	}
	secondary_color: {
		red: 241
		green: 242
		blue: 243
	}
}
Team { 
	id: 19
	location: "Orlando"
	name: "Magic"
	display_name: "Magic"
	abbreviation: "ORL"
	primary_color {
		red: 8
		green: 96
		blue: 168
	}
	secondary_color: {
		red: 196
		green: 206
		blue: 211
	}
}
Team { 
	id: 10
	location: "Houston"
	name: "Rockets"
	display_name: "Rockets"
	abbreviation: "HOU"
	primary_color {
		red: 212
		green: 0
		blue: 38
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 29
	location: "Memphis"
	name: "Grizzlies"
	display_name: "Grizzlies"
	abbreviation: "MEM"
	primary_color {
		red: 93
		green: 118
		blue: 168
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 28
	location: "Toronto"
	name: "Raptors"
	display_name: "Raptors"
	abbreviation: "TOR"
	primary_color {
		red: 206
		green: 15
		blue: 65
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 23
	location: "Sacramento"
	name: "Kings"
	display_name: "Kings"
	abbreviation: "SAC"
	primary_color {
		red: 57
		green: 57
		blue: 150
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 4
	location: "Chicago"
	name: "Bulls"
	display_name: "Bulls"
	abbreviation: "CHI"
	primary_color {
		red: 206
		green: 17
		blue: 65
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 13
	location: "Los Angeles"
	name: "Lakers"
	display_name: "Lakers"
	abbreviation: "LAL"
	primary_color {
		red: 84
		green: 37
		blue: 130
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 16
	location: "Minnesota"
	name: "Timberwolves"
	display_name: "T Wolves"
	abbreviation: "MIN"
	primary_color {
		red: 14
		green: 55
		blue: 100
	}
	secondary_color: {
		red: 196
		green: 206
		blue: 211
	}
}
Team { 
	id: 20
	location: "Philadelphia"
	name: "76ers"
	display_name: "76ers"
	abbreviation: "PHI"
	primary_color {
		red: 0
		green: 107
		blue: 182
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 5
	location: "Cleveland"
	name: "Cavaliers"
	display_name: "Cavaliers"
	abbreviation: "CLE"
	primary_color {
		red: 6
		green: 22
		blue: 66
	}
	secondary_color: {
		red: 253
		green: 187
		blue: 48
	}
}
Team { 
	id: 25
	location: "Oklahoma City"
	name: "Thunder"
	display_name: "Thunder"
	abbreviation: "OKC"
	primary_color {
		red: 198
		green: 124
		blue: 3
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 1
	location: "Atlanta"
	name: "Hawks"
	display_name: "Hawks"
	abbreviation: "ATL"
	primary_color {
		red: 0
		green: 43
		blue: 92
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 12
	location: "LA"
	name: "Clippers"
	display_name: "Clippers"
	abbreviation: "LAC"
	primary_color {
		red: 250
		green: 0
		blue: 40
	}
	secondary_color: {
		red: 241
		green: 242
		blue: 243
	}
}
Team { 
	id: 21
	location: "Phoenix"
	name: "Suns"
	display_name: "Suns"
	abbreviation: "PHX"
	primary_color {
		red: 35
		green: 0
		blue: 106
	}
	secondary_color: {
		red: 241
		green: 242
		blue: 243
	}
}
Team { 
	id: 7
	location: "Denver"
	name: "Nuggets"
	display_name: "Nuggets"
	abbreviation: "DEN"
	primary_color {
		red: 8
		green: 96
		blue: 168
	}
	secondary_color: {
		red: 253
		green: 185
		blue: 39
	}
}
Team { 
	id: 22
	location: "Portland"
	name: "Trail Blazers"
	display_name: "T Blazers"
	abbreviation: "POR"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 186
		green: 195
		blue: 201
	}
}
Team { 
	id: 17
	location: "Brooklyn"
	name: "Nets"
	display_name: "Nets"
	abbreviation: "BKN"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 26
	location: "Utah"
	name: "Jazz"
	display_name: "Jazz"
	abbreviation: "UTAH"
	primary_color {
		red: 6
		green: 20
		blue: 63
	}
	secondary_color: {
		red: 249
		green: 160
		blue: 27
	}
}
Team { 
	id: 18
	location: "New York"
	name: "Knicks"
	display_name: "Knicks"
	abbreviation: "NY"
	primary_color {
		red: 34
		green: 94
		blue: 168
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 8
	location: "Detroit"
	name: "Pistons"
	display_name: "Pistons"
	abbreviation: "DET"
	primary_color {
		red: 250
		green: 0
		blue: 44
	}
	secondary_color: {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 30
	location: "Charlotte"
	name: "Hornets"
	display_name: "Hornets"
	abbreviation: "CHA"
	primary_color {
		red: 29
		green: 16
		blue: 96
	}
	secondary_color: {
		red: 0
		green: 140
		blue: 168
	}
}
Team { 
	id: 11
	location: "Indiana"
	name: "Pacers"
	display_name: "Pacers"
	abbreviation: "IND"
	primary_color {
		red: 6
		green: 22
		blue: 66
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 9
	location: "Golden State"
	name: "Warriors"
	display_name: "Warriors"
	abbreviation: "GS"
	primary_color {
		red: 0
		green: 61
		blue: 165
	}
	secondary_color: {
		red: 253
		green: 185
		blue: 39
	}
}
Team { 
	id: 6
	location: "Dallas"
	name: "Mavericks"
	display_name: "Mavericks"
	abbreviation: "DAL"
	primary_color {
		red: 12
		green: 71
		blue: 157
	}
	secondary_color: {
		red: 196
		green: 206
		blue: 211
	}
}
Team { 
	id: 27
	location: "Washington"
	name: "Wizards"
	display_name: "Wizards"
	abbreviation: "WSH"
	primary_color {
		red: 14
		green: 55
		blue: 100
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 24
	location: "San Antonio"
	name: "Spurs"
	display_name: "Spurs"
	abbreviation: "SA"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 14
	location: "Miami"
	name: "Heat"
	display_name: "Heat"
	abbreviation: "MIA"
	primary_color {
		red: 0
		green: 0
		blue: 0
	}
	secondary_color: {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 15
	location: "Milwaukee"
	name: "Bucks"
	display_name: "Bucks"
	abbreviation: "MIL"
	primary_color {
		red: 0
		green: 56
		blue: 19
	}
	secondary_color: {
		red: 240
		green: 235
		blue: 210
	}
}
Team { 
	id: 3
	location: "New Orleans"
	name: "Pelicans"
	display_name: "Pelicans"
	abbreviation: "NO"
	primary_color {
		red: 0
		green: 42
		blue: 92
	}
	secondary_color: {
		red: 180
		green: 151
		blue: 90
	}
}
