Team { 
	id: 10
	location: "Toronto"
	name: "Maple Leafs"
	display_name: "Leafs"
	abbreviation: "TOR"
	primary_color {
		red: 0
		green: 32
		blue: 91
	}
	secondary_color {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 53
	location: "Arizona"
	name: "Coyotes"
	display_name: "Coyotes"
	abbreviation: "ARI"
	primary_color {
		red: 140
		green: 38
		blue: 51
	}
	secondary_color {
		red: 226
		green: 214
		blue: 181
	}
}
Team { 
	id: 7
	location: "Buffalo"
	name: "Sabres"
	display_name: "Sabres"
	abbreviation: "BUF"
	primary_color {
		red: 0
		green: 38
		blue: 84
	}
	secondary_color {
		red: 252
		green: 181
		blue: 20
	}
}
Team { 
	id: 52
	location: "Winnipeg"
	name: "Jets"
	display_name: "Jets"
	abbreviation: "WPG"
	primary_color {
		red: 4
		green: 30
		blue: 66
	}
	secondary_color {
		red: 162
		green: 170
		blue: 173
	}
}
Team { 
	id: 17
	location: "Detroit"
	name: "Red Wings"
	display_name: "Red Wings"
	abbreviation: "DET"
	primary_color {
		red: 200
		green: 16
		blue: 46
	}
	secondary_color {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 16
	location: "Chicago"
	name: "Blackhawks"
	display_name: "B Hawks"
	abbreviation: "CHI"
	primary_color {
		red: 206
		green: 17
		blue: 38
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 14
	location: "Tampa Bay"
	name: "Lightning"
	display_name: "Lightning"
	abbreviation: "TBL"
	primary_color {
		red: 0
		green: 32
		blue: 91
	}
	secondary_color {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 20
	location: "Calgary"
	name: "Flames"
	display_name: "Flames"
	abbreviation: "CGY"
	primary_color {
		red: 206
		green: 17
		blue: 38
	}
	secondary_color {
		red: 243
		green: 188
		blue: 82
	}
}
Team { 
	id: 30
	location: "Minnesota"
	name: "Wild"
	display_name: "Wild"
	abbreviation: "MIN"
	primary_color {
		red: 21
		green: 71
		blue: 52
	}
	secondary_color {
		red: 166
		green: 25
		blue: 46
	}
}
Team { 
	id: 28
	location: "San Jose"
	name: "Sharks"
	display_name: "Sharks"
	abbreviation: "SJS"
	primary_color {
		red: 0
		green: 98
		blue: 114
	}
	secondary_color {
		red: 229
		green: 114
		blue: 0
	}
}
Team { 
	id: 3
	location: "New York"
	name: "Rangers"
	display_name: "Rangers"
	abbreviation: "NYR"
	primary_color {
		red: 0
		green: 51
		blue: 160
	}
	secondary_color {
		red: 200
		green: 16
		blue: 46
	}
}
Team { 
	id: 13
	location: "Florida"
	name: "Panthers"
	display_name: "Panthers"
	abbreviation: "FLA"
	primary_color {
		red: 4
		green: 30
		blue: 66
	}
	secondary_color {
		red: 185
		green: 151
		blue: 91
	}
}
Team { 
	id: 26
	location: "Los Angeles"
	name: "Kings"
	display_name: "Kings"
	abbreviation: "LAK"
	primary_color {
		red: 162
		green: 170
		blue: 173
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 18
	location: "Nashville"
	name: "Predators"
	display_name: "Predators"
	abbreviation: "NSH"
	primary_color {
		red: 255
		green: 184
		blue: 28
	}
	secondary_color {
		red: 4
		green: 30
		blue: 66
	}
}
Team { 
	id: 87
	location: "Atlantic"
	name: "Atlantic All Stars"
	display_name: "Atlantic"
	abbreviation: "ATL"
	primary_color {
		red: 250
		green: 27
		blue: 27
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 90
	location: "Pacific"
	name: "Pacific All Stars"
	display_name: "Pacific"
	abbreviation: "PAC"
	primary_color {
		red: 17
		green: 189
		blue: 54
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 25
	location: "Dallas"
	name: "Stars"
	display_name: "Stars"
	abbreviation: "DAL"
	primary_color {
		red: 0
		green: 99
		blue: 65
	}
	secondary_color {
		red: 162
		green: 170
		blue: 173
	}
}
Team { 
	id: 23
	location: "Vancouver"
	name: "Canucks"
	display_name: "Canucks"
	abbreviation: "VAN"
	primary_color {
		red: 0
		green: 132
		blue: 61
	}
	secondary_color {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 12
	location: "Carolina"
	name: "Hurricanes"
	display_name: "Canes"
	abbreviation: "CAR"
	primary_color {
		red: 204
		green: 0
		blue: 0
	}
	secondary_color {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 4
	location: "Philadelphia"
	name: "Flyers"
	display_name: "Flyers"
	abbreviation: "PHI"
	primary_color {
		red: 250
		green: 70
		blue: 22
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 9
	location: "Ottawa"
	name: "Senators"
	display_name: "Senators"
	abbreviation: "OTT"
	primary_color {
		red: 200
		green: 16
		blue: 46
	}
	secondary_color {
		red: 198
		green: 146
		blue: 20
	}
}
Team { 
	id: 88
	location: "Metropolitan"
	name: "Metropolitan All Stars"
	display_name: "Metro"
	abbreviation: "MET"
	primary_color {
		red: 250
		green: 231
		blue: 27
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 22
	location: "Edmonton"
	name: "Oilers"
	display_name: "Oilers"
	abbreviation: "EDM"
	primary_color {
		red: 252
		green: 76
		blue: 2
	}
	secondary_color {
		red: 4
		green: 30
		blue: 66
	}
}
Team { 
	id: 19
	location: "St. Louis"
	name: "Blues"
	display_name: "Blues"
	abbreviation: "STL"
	primary_color {
		red: 0
		green: 47
		blue: 135
	}
	secondary_color {
		red: 255
		green: 184
		blue: 28
	}
}
Team { 
	id: 6
	location: "Boston"
	name: "Bruins"
	display_name: "Bruins"
	abbreviation: "BOS"
	primary_color {
		red: 252
		green: 181
		blue: 20
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 7461
	location: "America"
	name: "American All Stars"
	display_name: "America"
	abbreviation: "USA"
	primary_color {
		red: 50
		green: 113
		blue: 168
	}
	secondary_color {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 8
	location: "Montréal"
	name: "Canadiens"
	display_name: "Canadiens"
	abbreviation: "MTL"
	primary_color {
		red: 166
		green: 25
		blue: 46
	}
	secondary_color {
		red: 0
		green: 30
		blue: 98
	}
}
Team { 
	id: 89
	location: "Central"
	name: "Central All Stars"
	display_name: "Central"
	abbreviation: "CEN"
	primary_color {
		red: 20
		green: 17
		blue: 189
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 5
	location: "Pittsburgh"
	name: "Penguins"
	display_name: "Penguins"
	abbreviation: "PIT"
	primary_color {
		red: 255
		green: 184
		blue: 28
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 54
	location: "Las Vegas"
	name: "Golden Knights"
	display_name: "Knights"
	abbreviation: "VGK"
	primary_color {
		red: 180
		green: 151
		blue: 90
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 55
	location: "Seattle"
	name: "Kraken"
	display_name: "Kraken"
	abbreviation: "SEA"
	primary_color {
		red: 0
		green: 22
		blue: 40
	}
	secondary_color {
		red: 153
		green: 217
		blue: 217
	}
}
Team { 
	id: 2
	location: "New York"
	name: "Islanders"
	display_name: "Islanders"
	abbreviation: "NYI"
	primary_color {
		red: 0
		green: 48
		blue: 135
	}
	secondary_color {
		red: 252
		green: 76
		blue: 2
	}
}
Team { 
	id: 21
	location: "Colorado"
	name: "Avalanche"
	display_name: "Avalanche"
	abbreviation: "COL"
	primary_color {
		red: 35
		green: 97
		blue: 146
	}
	secondary_color {
		red: 217
		green: 69
		blue: 116
	}
}
Team { 
	id: 15
	location: "Washington"
	name: "Capitals"
	display_name: "Capitals"
	abbreviation: "WSH"
	primary_color {
		red: 4
		green: 30
		blue: 66
	}
	secondary_color {
		red: 200
		green: 16
		blue: 46
	}
}
Team { 
	id: 29
	location: "Columbus"
	name: "Blue Jackets"
	display_name: "B Jackets"
	abbreviation: "CBJ"
	primary_color {
		red: 4
		green: 30
		blue: 66
	}
	secondary_color {
		red: 200
		green: 16
		blue: 46
	}
}
Team { 
	id: 24
	location: "Anaheim"
	name: "Ducks"
	display_name: "Ducks"
	abbreviation: "ANA"
	primary_color {
		red: 181
		green: 152
		blue: 90
	}
	secondary_color {
		red: 255
		green: 255
		blue: 255
	}
}
Team { 
	id: 1
	location: "New Jersey"
	name: "Devils"
	display_name: "Devils"
	abbreviation: "NJD"
	primary_color {
		red: 200
		green: 16
		blue: 46
	}
	secondary_color {
		red: 0
		green: 0
		blue: 0
	}
}
Team { 
	id: 7460
	location: "Canada"
	name: "Canadian All Stars"
	display_name: "Canada"
	abbreviation: "CA"
	primary_color {
		red: 209
		green: 23
		blue: 23
	}
	secondary_color {
		red: 255
		green: 255
		blue: 255
	}
}
